### PR TITLE
Added announcement and publications

### PR DESCRIPTION
**Pull request by chelsea-brown**

### CODE REVIEW

**Review by danielpastor97 — CHANGES_REQUESTED** [review]
Hi Chelse, there is just a small change that I would want you to do before approving the PR. If you can comment [this line](https://github.com/chelsea-brown/Martini-Force-Field-Initiative.github.io/blob/main/docs/announcements/posts/2024-11-11-groningen-positions/index.qmd#L9), from:
```
image: ""      # path to image file (optional): If not provided, the default image for announcements will be used
```
to
```
# image: ""      # path to image file (optional): If not provided, the default image for announcements will be used
```
Or just remove it completely. That way we will make sure that the announcement uses the default announcement image, as no other image was provider. The difference is that if we leave the variable assigned as "" it will still see it as as an alternative initialized value and won't use the default image.

Cheers!
Daniel

**Comment by chelsea-brown** [comment]
Hi Daniel, sorry about that oversight - should all be sorted now!

Thanks,
Chelsea

**Review by danielpastor97 — APPROVED** [review]
Thanks @chelsea-brown  , I will merge the changes to `main` now. The website should reflect the updates immediately afterwards.

**Comment by danielpastor97** [comment]
Updates confirmed at `cgmartini.nl`!! 

image

**Comment by chelsea-brown** [comment]
Hey, very sorry just noticed a typo that I thought I'd fixed. It says on bahlf instead on behalf in the author section. Would you be able to fix it quickly or would the quickest way be me with another pull request?

**Pull request merged**
