### PR TITLE
updated protein 1 tutorial

### PR DESCRIPTION
**Pull request by csbrasnett**
One user over in the [discussion forum](https://github.com/orgs/Martini-Force-Field-Initiative/discussions/5) has had issues with working out the input string for secondary structure specification. From my memory, the previous version of the tutorial had -dssp as the default argument, but I guess when it was revised that was changed for people who didn't have it installed? 

However, I'm not sure if how it's been revised is particularly clear for people who aren't already familiar with martinize2 functionality, so I've tried having a go at a small rewrite to hopefully reintroduce some clarity. I realise this is a matter of personal opinion, so please let me know what you think!

### CODE REVIEW

**Comment by Lp0lp** [comment]
Heyo! We've talked about reviewing a few tutorials and this was definitely one of them. Especially because a lot of it is now deprecated (the entire gomodel routine). If we are fixing part of it I would suggest we also fix this bit? 

If you're interested @csbrasnett you could have a go at it, or I can also have a look in the next few days. Basically making the tutorial in line with the GoMartini paper, using martinize instead of the creategovirt.py script.

I would say we could then have Paulo @paulocts , for example, give it a read through before we merge this. What do you think?

**Comment by csbrasnett** [comment]
Ah nice! Yep happy to have a look at the rest of the tutorial as well so we get this done in one PR. I’ll have a look in the next few days and push it so you guys can have a look

**Comment by KasperBuskPedersen** [comment]
@csbrasnett please go ahead and write a small section of how to set up OLIVES if you find that useful. You can basically just copy paste from the OLIVES github. Alternatively just write that OLIVES is an alternative and link the github? Unfortunately I don't have time to write or test that atm.

**Comment by csbrasnett** [comment]
I think it'd be nice to have everything in one place as much as possible, I'll try to cook something up based on what you've done and also link through for more examples with the varying quaternary structure interaction strength so we don't overcomplicate too. 

This is defo out of scope atm, but is there any desire to implement olives into martinize2 at some point? I realise it'd be a lot of work, but it might be nice in terms of workflow optimisation? I'd definitely appreciate it for one (and would be up for trying to do it when I have some time)!

**Comment by KasperBuskPedersen** [comment]
@csbrasnett Actually, I think there is a risk of doing new users a disservice by automating it too much. Since olives is more or less additive to the standard martini model, it makes sense to keep them separate.

With the new protein model of Luis', there are several reasons to keep martinize2 and olives as two separate calls, e.g. multistate olives would require you to martinize two proteins in 2 separate calls followed by one olives call etc.. 

I wont be able to maintain martinize2 going forward, but can support olives alone. From a software maintanece standpoint it is also not good to combine everything into a mega program. 

Though, we could add olives to vermouth, so it would become a command line call like martinize2, such that you won't have to carry the python script around, but again one could just add olives to their .bashrc. 

Best Kasper

**Comment by csbrasnett** [comment]
@Lp0lp @paulocts @KasperBuskPedersen hopefully this satisfies everyone now!

**Comment by csbrasnett** [comment]
@Lp0lp did you get a chance to have a look yet?

**Comment by Lp0lp** [comment]
@csbrasnett not yet sorry. Had to tackle a couple of grants and currently on the road. Worst case I'll have it checked out by Monday. Sorry! 
BTW I think it might be interesting to include the old protein tutorial on the deprecated tutorial sections. What do you think? Might have some benefit to someone trying to reproduce the old gomartini implementation.

**Comment by Lp0lp** [comment]
Heyo!

@csbrasnett I am happy with the tutorial. I tweaked some wording and some formatting but nothing major. I've sent it to @paulocts so that he could have a look as well.

I added the old iteration of the tutorial to the legacy tutorials.

I also added to the tutorial list the two new collab tutorials @mnmelo and @martincalvelo cooked up. They end up working great in Quarto, since quarto automatically renders `.ipynb` as a webpage quite well. Only thing I changed was at the header to show authorship of the tutorial. @mnmelo and @martincalvelo I added the tutorials on the list as 4.1 and 4.2 since they are a natural continuation of tutorial 4 but I am open to listing them differently. What do you think?

I updated the tutorial author list to include @csbrasnett and @martincalvelo .

**Comment by csbrasnett** [comment]
great, thanks! 

All sounds good to me. To note, I'm currently looking at changing the behaviour of `-scfix` so it's used by default [here](https://github.com/marrink-lab/vermouth-martinize/pull/621). Once this is changed in martinize2 we can update here as well, so hold off on merging!

**Comment by mnmelo** [comment]
Hey, this looks great. I'd add a caveat here, though:
Our tutorials were prepared for colab and if run blindly will download and install gromacs and dssp binaries as well as some pip dependencies. The most breaking stuff will probably fail unless run as root because it will attempt to unpack binaries onto system directories, but I imagine it can still be confusing...

Of course, non-Colab users should just provide their own dependencies and skip those installation cells. What's your take?

**Comment by Lp0lp** [comment]
On all the other tutorials we expect the user to already have all the
required compilations ready to go, so I don't see skipping these cells as
anything too confusing/limiting in comparison. Maybe I am wrong though...
In any case, these two tutorials can be a sort of test to see if people run
into issues in case we want to expand on this kind of tutorial.

Big warning at the top reinforcing these were prepared for colab and to
skip the installation/step 0 cells If running on own compilations, I guess?

Alternatively, maybe adjust the notebook such that it knows whether it is
running in a collab or not?
If in_collab:compile; else: skip
Something like this:
https://stackoverflow.com/questions/53581278/test-if-notebook-is-running-on-google-colab


Manuel Nuno Melo ***@***.***> escreveu (segunda, 21/10/2024
à(s) 18:13):

**Comment by mnmelo** [comment]
I like that kind of automation. It's safer. @martincalvelo, do you think you could try to incorporate that?

BTW, the code doesn't actually compile. It  downloads a zip of already compiled GROMACS that I prepared and make available.

**Comment by csbrasnett** [comment]
@Lp0lp, @danielpastor97 I think some users have had issues with the tutorial especially now that `-govs-moltype` has been removed from martinize. The changes are already there, please can this be merged asap?

**Comment by Lp0lp** [comment]
I'll do the final tweaks today and then it should be good to go.

**Comment by danielpastor97** [comment]
Let me know if you need any assistance @Lp0lp . Looking good as far as I can tell!

**Comment by Lp0lp** [comment]
All that was left to do was updating Martin and Manel's tutorials. Good to go on my end!

**Review by danielpastor97 — CHANGES_REQUESTED** [review]
@csbrasnett I have requested some small changes to ensure the Github Action we have implemented to deploy the website runs smoothly.  Everything else looks great to me, thank you so much! 

Once these are resolved I will proceed to merge it to main rigth away. Hopefully we'll see more updates like this for the other tutorials in the near future.

**Comment by danielpastor97** [comment]
@csbrasnett Can you please check again the requested changes? I see you added two commits, but these don't resolve the points I mentioned. 

1. In the header of the announcement, the syntax is not correct. If we use the `|` symbol for an attribute, we can not write text right after it. In this case, that happens in the `description:` attribute, which prevents Quarto from compiling successfully. We can either remove the `|` symbol or use the symbol and add the text in the next line using a tab (as suggested in my review). 
2. In addition, the changes to the links were intended for the old `ProteinsI` tutorial that is now in legacy, not the new one. I will unresolve the requested changes so you can look at the comments. If you copy/paste the suggestions everything should be fine. Please make sure to undo the changes in the new tutorial added in the last commit, as these created additional broken links.

As soon as these changes are complete and the compilation of the website is running smoothly, I will proceed with the merge. Thanks again!🙂

**Comment by csbrasnett** [comment]
Apologies for messing that up - hope all good now!

**Pull request merged**
